import csv

with open('current_email_list.csv', newline='') as e: # Data generated by https://mockaroo.com/
    reader = csv.reader(e)
    current_list = list(reader)
print("----------------Current List------------------")
print(sorted(current_list))
print("\n")

with open('updated_email_list.csv', newline='') as f: # Data generated by https://mockaroo.com/
    reader = csv.reader(f)
    new_list = list(reader)
print("------------------New List--------------------")
print(sorted(new_list))
print("\n")

# for i in new_list:
#     for j in current_list:
#         if i == j:
#             print(i)

print("**********Items in new_list not in current_list**********")
for i in new_list:
    if i not in current_list:
        print(i)
print("\n")

print("**********Items in current_list not in new_list**********")
for x in current_list:
    if x not in new_list:
        print(x)
print("\n")